data_home: /lustre/fswork/projects/rech/lzs/uhq13gg/benchmark-allreduce

plot_configs:
  Communication Ratio:
    plot_kind: communication_ratio
    scale: linear
    display_method: both
  Run Time:
    plot_kind: run_curves
    scale: semilog-x
    with_quantiles: true
  Communication Time:
    metrics_metric: comm_time
    plot_kind: metrics
    scale: linear
