objective:
  all-reduce:
    device: "cuda"
    local_batch_size: [128]

dataset:
  convnext:
    variant: convnextv2_tiny
    image_size: 224

solver:
  all-reduce:
    slurm_nodes: [1, 2, 4, 8]
  all-reduce-nolock:
    slurm_nodes: [1, 2, 4, 8]
  ddp:
    slurm_nodes: [1, 2, 4, 8]

parallel_config: config_parallel_h100.yml
n_repetitions: 10
timeout: 100000
