objective:
  all-reduce:
    device: "cuda"
    local_batch_size: [12000]

dataset:
  mlp:
    d: [4000]
    layers: [1, 16]

solver:
  all-reduce:
    slurm_nodes: [1, 2, 4, 8]
  all-reduce-nolock:
    slurm_nodes: [1, 2, 4, 8]
  ddp:
    slurm_nodes: [1, 2, 4, 8]

parallel_config: configs/config_parallel_v100.yml
n_repetitions: 10
timeout: 100000
